services:
  postgres:
    container_name: nest-forum-pg
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestforum
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-forum-cache
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
